---

- name: Copy the java executable
  win_copy: src=JavaSetup8u101.exe dest='C:\\JavaSetup8u101.exe'

- name: Copy the java configuration file
  win_copy: src=myconf.cfg dest='C:\\myconf.cfg'

- name: Installing java
  raw: 'C:/JavaSetup8u101.exe INSTALLCFG=C:/myconf.cfg'

- name: Get actual PATH
  raw: $ENV:PATH
  register: path_out
  
- name: Add java to path 
  raw: SETX /M PATH "$ENV:PATH;C:\java\jre\bin"
  when: path_out.stdout.find('jre') == -1
    
